spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        format_sql: true
        show_sql: true
        default_batch_fetch_size: 20

  devtools:
    livereload:
      enabled: true

logging.level:
  org.hibernate.SQL: debug